# Generated by Django 4.0.4 on 2022-05-28 12:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo'),
        ),
    ]
